CREATE DATABASE autorite;
CREATE USER autorite IDENTIFIED WITH mysql_native_password BY "autorite@123";
GRANT ALL PRIVILEGES ON autorite.* TO autorite;
FLUSH PRIVILEGES;
use autorite;
CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(200) NOT NULL,
  password varchar(100) NOT NULL,
  role ENUM("user", "admin") DEFAULT "user",
  isEmailVerified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE tokens(
  id INT PRIMARY KEY AUTO_INCREMENT,
  token VARCHAR(300) NOT NULL,
  user_id INT NOT NULL,
  type ENUM ("refresh", "resetPassword", "verifyEmail"),
  expires TIMESTAMP NOT NULL,
  blacklisted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);